# default value: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/theme-light.toml

[flavor]
dark = ""
light = ""

[tabs]
active = { bg = "lightblue", bold = true }
inactive = { fg = "lightblue", bg = "gray" }

[mode]
normal_main = { bg = "lightblue", bold = true }

[indicator]
preview = { underline = false }

[which]
cand = { fg = "lightblue" }
desc = { fg = "lightyellow" }

[filetype]
rules = [
  # Fallback
  { url = "*/", bold = true, fg = "lightblue" },
]
